default:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

build-image:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - export JAVA_VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f1)
    - export LATEST_TAG=${JAVA_VERSION}-latest
    - docker build --build-arg="OPEN_JDK_VERSION=${JAVA_VERSION}" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:$LATEST_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$LATEST_TAG
