default:
  image:
    name: git.alisaqaq.moe:443/alisa-lab-containers/dependency_proxy/containers/docker:25.0.3
    pull_policy: if-not-present
  services:
    - name: git.alisaqaq.moe:443/alisa-lab-containers/dependency_proxy/containers/docker:25.0.3-dind
      pull_policy: if-not-present
      alias: docker
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER --username $CI_DEPENDENCY_PROXY_USER --password-stdin

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-image:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - export JAVA_VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f1)
    - export LATEST_TAG=${JAVA_VERSION}-latest
  script:
    - docker build --build-arg="OPEN_JDK_VERSION=${JAVA_VERSION}" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:$LATEST_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$LATEST_TAG
